version: "3.7"

services:
  react_classic:
    build:
      context: .
      dockerfile: Classic.Dockerfile
    container_name: react_demo_classic
    # environment:
    #   DISPLAY: $DISPLAY
    networks:
      - dev-network
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "1337:80"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    # command: "tail -f /dev/null"

  react_electron:
    build:
      context: .
      dockerfile: Electron.Dockerfile
    container_name: react_demo_electron
    environment:
      DISPLAY: $DISPLAY
    networks:
      - dev-network
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: "tail -f /dev/null"

networks:
  dev-network:
    driver: bridge
    external:
      name: fcs_network
